spring:
  datasource:
    url: "jdbc:mariadb://localhost:3306/spring"
    username: "spring"
    password: "password"
  jpa:
    hibernate:
      ddl-auto: "update"
    show-sql: true
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.MariaDBDialect"
  profiles:
    active: dev
server:
  address: "127.0.0.1"
  port: 2077
  compression:
    enabled: true
  http2:
    enabled: true
springlify:
  platform:
    text-converter-mode: legacy
plugin:
  # Prints debug information to the console.
  # Please note that this can cause performance issues.
  debug: true
  bank:
    # The name of the national bank.
    name: "Bank of District"