spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: username
    password: password
  h2:
    console:
      enabled: true
  sql:
    init:
      schema-locations: classpath:schema.sql
